//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dll.rc
//
#define IDD_DIALOG1                     101
#define IDB_BITMAP1                     111
#define IDB_BITMAP2                     112
#define IDB_BITMAP3                     113
#define IDB_BITMAP4                     114
#define IDB_BITMAP5                     117
#define IDB_BITMAP6                     147
#define IDB_BITMAP7                     148
#define IDB_BITMAP8                     149
#define IDB_BITMAP9                     150
#define IDB_BITMAP10                    152
#define IDB_BITMAP11                    153
#define IDB_BITMAP12                    154
#define IDB_BITMAP13                    155
#define IDB_BITMAP14                    156
#define IDB_BITMAP15                    157
#define IDB_BITMAP16                    158
#define IDB_BITMAP17                    159
#define IDB_BITMAP18                    160
#define IDC_BUTTON1                     1000
#define IDC_BUTTON_B                    1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON3                     1002
#define IDC_BUTTON4                     1003
#define IDC_BUTTON5                     1004
#define IDC_BMP1                        1006
#define IDC_BMP2                        1007
#define IDC_BMP3                        1008
#define IDC_BMP4                        1009
#define IDC_BMP5                        1010
#define IDC_BUTTON6                     1015
#define IDC_BMP6                        1015
#define IDC_BMP10                       1016
#define IDC_BMP7                        1017
#define IDC_BMP8                        1018
#define IDC_BMP9                        1019
#define IDC_BMP11                       1020
#define IDC_BMP12                       1021
#define IDC_BMP13                       1022
#define IDC_BMP14                       1023
#define IDC_BMP15                       1024
#define IDC_BMP16                       1030
#define IDC_BUTTON_BA                   1032
#define IDC_BUTTON_C                    1034
#define IDC_BUTTON_CA                   1035
#define IDC_BUTTON_CC                   1036
#define IDC_BUTTON_5                    1036
#define IDC_BUTTON_CD                   1037
#define IDC_BUTTON_6                    1037
#define IDC_BUTTON_CM                   1038
#define IDC_BUTTON_7                    1038
#define IDC_BUTTON_RC                   1039
#define IDC_BUTTON_T                    1040
#define IDC_BUTTON_TA                   1041
#define IDC_BUTTON_TAWIR                1042
#define IDC_BUTTON_TC                   1043
#define IDC_BUTTON_TJ                   1044
#define IDC_BUTTON_DP                   1045
#define IDC_BUTTON_8                    1045
#define IDC_BUTTON_TP                   1046
#define IDC_BUTTON_TR                   1047
#define IDC_BMP17                       1048
#define IDC_BUTTON_DPWIR                1049
#define IDC_BMP18                       1050
#define IDC_CLOSE                       1050
#define IDC_BUTTON_WTA                  1051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
